export const featureStructureAudit = [
  {
    feature: 'admin',
    routeFamily: '/admin',
    pageFile: 'features/admin/AdminPage.jsx',
    hookFiles: ['features/admin/useAdminData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Folder structure is otherwise standardized and supports both users and EMP master surfaces.']
  },
  {
    feature: 'approvals',
    routeFamily: '/approvals',
    pageFile: 'features/approvals/ApprovalsPage.jsx',
    hookFiles: ['features/approvals/useApprovalsData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Feature folder is structurally complete apart from documentation parity.']
  },
  {
    feature: 'attendance',
    routeFamily: '/attendance',
    pageFile: 'features/attendance/AttendancePage.jsx',
    hookFiles: ['features/attendance/useAttendanceData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Attendance has a strong internal split across entry, range, summary, and tables.']
  },
  {
    feature: 'auth',
    routeFamily: '/login, /client/login',
    pageFile: 'features/auth/LoginPage.jsx + features/auth/ClientLoginPage.jsx',
    hookFiles: ['provider-driven auth state'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: ['dedicated useAuth hook layer if wanted later'],
    notes: ['Auth is provider-oriented instead of a single useXData hook, which is fine for this feature type.']
  },
  {
    feature: 'client-portal',
    routeFamily: '/client/*',
    pageFile: 'features/client-portal/ClientDashboardPage.jsx + ClientTicketsPage.jsx + ClientInvoicesPage.jsx + ClientReportsPage.jsx',
    hookFiles: [
      'features/client-portal/useClientDashboardData.js',
      'features/client-portal/useClientInvoicesData.js',
      'features/client-portal/useClientReportsData.js',
      'features/client-portal/useClientTicketWorkspace.js',
      'features/client-portal/useClientTicketsData.js',
      'features/client-portal/useClientPortalResource.js'
    ],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['This is the most mature multi-page feature folder in the client route family.']
  },
  {
    feature: 'client-social',
    routeFamily: '/client/social',
    pageFile: 'features/client-social/ClientSocialPage.jsx',
    hookFiles: ['features/client-social/useClientSocialData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Feature folder follows the target pattern well.']
  },
  {
    feature: 'clients-portal',
    routeFamily: '/clients-portal',
    pageFile: 'features/clients-portal/ClientsPortalPage.jsx',
    hookFiles: ['features/clients-portal/useClientsPortalData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Admin-side clients portal structure is otherwise aligned with the production pattern.']
  },
  {
    feature: 'dashboard',
    routeFamily: '/',
    pageFile: 'features/dashboard/DashboardPage.jsx',
    hookFiles: ['features/dashboard/useDashboardData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Employee dashboard structure is solid but not yet documented feature-locally.']
  },
  {
    feature: 'expenses',
    routeFamily: '/expenses',
    pageFile: 'features/expenses/ExpensesPage.jsx',
    hookFiles: ['features/expenses/useExpensesData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Feature shape is clean and production-style apart from missing local docs.']
  },
  {
    feature: 'fms',
    routeFamily: '/fms-tracker',
    pageFile: 'features/fms/FmsPage.jsx',
    hookFiles: ['features/fms/useFmsData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Feature is structurally consistent; missing items are mainly documentation and parity work.']
  },
  {
    feature: 'forms-portal',
    routeFamily: '/forms-portal',
    pageFile: 'features/forms-portal/FormsPortalPage.jsx',
    hookFiles: ['features/forms-portal/useFormsPortalData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['The folder pattern is standardized, with parity gaps mainly inside dialogs and access behavior.']
  },
  {
    feature: 'management-dashboard',
    routeFamily: '/management-dashboard',
    pageFile: 'features/management-dashboard/ManagementDashboardPage.jsx',
    hookFiles: ['features/management-dashboard/useManagementDashboardData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Management dashboard follows the target pattern well, though feature parity remains incomplete.']
  },
  {
    feature: 'reports',
    routeFamily: '/reports',
    pageFile: 'features/reports/ReportsPage.jsx',
    hookFiles: ['features/reports/useReportsData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Reports folder is structurally complete and awaits more parity-specific work than folder work.']
  },
  {
    feature: 'tickets',
    routeFamily: '/ticket-system',
    pageFile: 'features/tickets/TicketSystemPage.jsx',
    hookFiles: ['features/tickets/useTicketSystemData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Feature shape is standardized; modal/dialog extraction is the larger remaining issue.']
  },
  {
    feature: 'todo',
    routeFamily: '/todo',
    pageFile: 'features/todo/TodoPage.jsx',
    hookFiles: ['features/todo/useTodoData.js'],
    hasApi: true,
    hasManifest: true,
    hasContracts: true,
    hasServices: true,
    hasComponentsIndex: true,
    hasReadme: true,
    missingOrUneven: [],
    notes: ['Todo is one of the cleaner standalone feature folders already matching the target pattern.']
  }
];

export const featureStructurePattern = {
  expectedCoreFiles: ['Page.jsx or pages', 'hook/data owner', 'api.js', 'manifest.js', 'contracts/index.js', 'services/index.js', 'components/index.js'],
  optionalButPreferred: ['README.md', 'feature-local tests later if added', 'additional hooks for large multi-page features']
};
