// Message wording copied from appscript/code.gs. Generated by extractWhatsAppTemplates.js.
export const legacyWhatsAppTemplates = {
  welcome: ({newUser}) => (`🎉 *WELCOME TO WORK TRACK SYSTEM* 🎉\n` +
          `---------------------------------\n` +
          `Hello *${newUser['Employee Name']}*,\n\n` +
          `Welcome to the team! Your official Work Track Portal account has been created successfully.\n\n` +
          `🔐 *Your Login Credentials:*\n` +
          `• *Employee ID:* *${newUser['Employee ID']}*\n` +
          `• Password admin/Mongo employee master me set hone ke baad login active hoga.\n\n` +
          `👉 Kripya niche diye gaye link par click karke login karein aur profile me jaakar apna password turant change karein.\n\n` +
          `~ Work Track System`),
  ticketAssigned: ({assignedUserNotify,newTicket,tatVal,planDateStr,assignContext}) => (`🚨 *NEW TICKET ASSIGNED ALERT* 🚨\n` +
        `---------------------------------\n` +
        `Hello *${assignedUserNotify['Employee Name']}*,\n\n` +
        `A brand new ticket has been assigned to you. Please check the details:\n\n` +
        `🎫 *Ticket ID:* *${newTicket['Ticket ID']}*\n` +
        `🏢 *Client Name:* *${newTicket.Name}*\n` +
        `📂 *Category:* *${newTicket['Task Category'] || 'N/A'}*\n` +
        `⚡ *Priority:* *${newTicket.Priority}*\n` +
        `🎯 *Allocated TAT:* *${tatVal}*\n` +
        `📅 *Planned / Target Date:* *${planDateStr}*\n` +
        `📝 *Task Description:* ${newTicket['Task Description']}\n\n` +
        `${assignContext}\n\n` +
        `👉 Kindly open the portal and start the timer when you begin working.\n\n` +
        `~ Work Track System`),
  ticketReassigned: ({newUser,ticketId,clientName,priority,tatVal,planDateStr,fullDesc,assignerText,remarks}) => (`🔄 *TICKET REASSIGNED ALERT* 🔄\n` +
          `---------------------------------\n` +
          `Hello *${newUser['Employee Name']}*,\n\n` +
          `A ticket has been reassigned to you. Please review the details:\n\n` +
          `🎫 *Ticket ID:* *${ticketId}*\n` +
          `🏢 *Client Name:* *${clientName}*\n` +
          `📂 *Priority:* *${priority}*\n` +
          `🎯 *Allocated TAT:* *${tatVal}*\n` +
          `📅 *Target / Plan Date:* *${planDateStr}*\n` +
          `📝 *Task Details:* ${fullDesc}\n\n` +
          `${assignerText}\n` +
          `💬 *Instructions/Remarks:* *${remarks || 'None'}*\n\n` +
          `👉 Portal open karein aur jaldi se kaam shuru karein!\n\n` +
          `~ Work Track System`),
  ticketApproval: ({approverUser,ticketId,ticketRow,category,actionBy,fullDesc,assignedTAT,actualTimeTaken,userRemarks}) => (`⏳ *APPROVAL REQUIRED: TASK COMPLETED* ⏳\n` +
          `---------------------------------\n` +
          `Hello *${approverUser['Employee Name']}*,\n\n` +
          `One of your team member's tasks is waiting for your verification & approval:\n\n` +
          `🎫 *Ticket ID:* *${ticketId}*\n` +
          `🏢 *Client Name:* *${ticketRow['Name']}*\n` +
          `📂 *Category:* *${category}*\n` +
          `👤 *Completed By:* *${actionBy}*\n` +
          `📝 *Task Details:* ${fullDesc}\n\n` +
          `🎯 *Assigned TAT:* *${assignedTAT}*\n` +
          `⏱️ *Actual Time Taken:* *${actualTimeTaken}*\n` +
          `💬 *User Remarks / Notes:* *${userRemarks}*\n\n` +
          `👉 Kripya apne admin dashboard me jaakar is ticket ko verify aur close/rework karein.\n\n` +
          `~ Work Track System`),
  ticketClosed: ({ticketId,clientName,category,adminUser,adminRole,description,remarks}) => (`🎉 *TICKET APPROVED & CLOSED* 🎉\n` +
          `---------------------------------\n` +
          `🎫 *Ticket ID:* *${ticketId}*\n` +
          `🏢 *Client Name:* *${clientName}*\n` +
          `📂 *Category:* *${category}*\n` +
          `👤 *Approved By:* *${adminUser['Employee Name']}* (${adminRole})\n` +
          `📝 *Task Details:* ${description}\n\n` +
          `💬 *Approver Remarks:* *${remarks || 'No remarks provided.'}*\n\n` +
          `🏆 Great job! Your task is officially closed.\n\n` +
          `~ Work Track System`),
  ticketRework: ({ticketId,clientName,category,adminUser,adminRole,description,remarks}) => (`⚠️ *REWORK REQUIRED ALERT* ⚠️\n` +
          `---------------------------------\n` +
          `🎫 *Ticket ID:* *${ticketId}*\n` +
          `🏢 *Client Name:* *${clientName}*\n` +
          `📂 *Category:* *${category}*\n` +
          `👤 *Returned By:* *${adminUser['Employee Name']}* (${adminRole})\n` +
          `📝 *Task Details:* ${description}\n\n` +
          `💬 *Feedback / Instructions:* *${remarks || 'Please check and fix.'}*\n\n` +
          `📌 Kripya di gayi suggestions ke hisaab se task thik karke dubara submit karein.\n\n` +
          `~ Work Track System`),
  ticketHrApproved: ({ticketId,clientName,category,adminUser,description}) => (`⏳ *HR APPROVED & VERIFIED* ⏳\n` +
          `---------------------------------\n` +
          `🎫 *Ticket ID:* *${ticketId}*\n` +
          `🏢 *Client Name:* *${clientName}*\n` +
          `📂 *Category:* *${category}*\n` +
          `👤 *HR Evaluator:* *${adminUser['Employee Name']}*\n` +
          `📝 *Task:* ${description}\n\n` +
          `✅ *Status:* Ticket has been successfully verified by HR!\n\n` +
          `~ Work Track System`),
  leaveRequest: ({rec,leaveData,sDateStr,eDateStr}) => (`⏳ *NEW LEAVE REQUEST SUBMITTED* ⏳\n` +
          `---------------------------------\n` +
          `Hello *${rec.name}*,\n\n` +
          `A new Leave request has been submitted and is waiting for your approval:\n\n` +
          `👤 *Employee Name:* *${leaveData['Employee Name']}* (${leaveData['Employee ID']})\n` +
          `📌 *Leave Type:* *${leaveData['Leave Type']}*\n` +
          `📅 *Duration:* *${sDateStr}* to *${eDateStr}* (${leaveData['Day Type']})\n` +
          `📝 *Reason:* ${leaveData['Reason']}\n\n` +
          `👉 Please check your pending approvals dashboard to review and approve/reject this request.\n\n` +
          `~ Work Track System`),
  intimationRequest: ({rec,intimationData,dateStr}) => (`📢 *NEW WORK INTIMATION SUBMITTED* 📢\n` +
          `---------------------------------\n` +
          `Hello *${rec.name}*,\n\n` +
          `An employee has submitted a new Work Intimation:\n\n` +
          `👤 *Employee Name:* *${intimationData['Employee Name']}* (${intimationData['Employee ID']})\n` +
          `📌 *Intimation Type:* *${intimationData['Intimation Type']}*\n` +
          `📅 *Date:* *${dateStr}*\n` +
          `📝 *Details/Reason:* ${intimationData['Reason']}\n\n` +
          `👉 Please review the details in your admin panel.\n\n` +
          `~ Work Track System`),
  requestResult: ({emoji,type,statusLabel,employeeObj,subType,dateStr,reason,remarks}) => (`${emoji} *YOUR ${type.toUpperCase()} REQUEST HAS BEEN ${statusLabel}* ${emoji}\n` +
            `---------------------------------\n` +
            `Hello *${employeeObj['Employee Name']}*,\n\n` +
            `Your applied ${type} request has been reviewed by the Admin/HR:\n\n` +
            `📌 *Request Type:* *${subType}*\n` +
            `📅 *Date:* *${dateStr}*\n` +
            `📝 *Your Reason:* ${reason}\n\n` +
            `⚙️ *Action Status:* *${statusLabel}*\n` +
            `💬 *Admin Remarks/Feedback:* *${remarks || 'Processed.'}*\n\n` +
            `~ Work Track System`),
  expenseRequest: ({rec,expenseData}) => (`💰 *NEW EXPENSE CLAIM SUBMITTED* 💰\n` +
          `---------------------------------\n` +
          `Hello *${rec.name}*,\n\n` +
          `A new expense claim has been filed and requires your verification:\n\n` +
          `👤 *Claimed By:* *${expenseData['Employee Name']}* (${expenseData['Employee ID']})\n` +
          `📌 *Expense Type:* *${expenseData.Type}*\n` +
          `💵 *Amount:* *₹${parseFloat(expenseData.Amount).toFixed(2)}*\n` +
          `📝 *Description:* ${expenseData.Description}\n\n` +
          `👉 Please review this claim in your admin panel.\n\n` +
          `~ Work Track System`),
  expenseResult: ({emoji,status,employee,expenseId,expenseRow,admin,remarks}) => (`${emoji} *EXPENSE CLAIM ${status.toUpperCase()}* ${emoji}\n` +
          `---------------------------------\n` +
          `Hello *${employee['Employee Name']}*,\n\n` +
          `Your submitted expense claim has been processed by the Admin:\n\n` +
          `🎫 *Expense ID:* *${expenseId}*\n` +
          `📌 *Type:* *${expenseRow.Type}*\n` +
          `💵 *Amount:* *₹${parseFloat(expenseRow.Amount).toFixed(2)}*\n` +
          `📝 *Description:* ${expenseRow.Description}\n\n` +
          `⚙ *Action:* *${status.toUpperCase()}*\n` +
          `👤 *Approver:* *${admin['Employee Name']}*\n` +
          `💬 *Admin Remarks:* *${remarks || 'No remarks provided.'}*\n\n` +
          `~ Work Track System`),
  approvalTransfer: ({targetManager,currentManager,ticketId,clientName,category,completedByName,completedBy,description,remarks}) => (`🔄 *APPROVAL AUTHORITY TRANSFERRED* 🔄\n` +
        `---------------------------------\n` +
        `Hello *${targetManager['Employee Name']}*,\n\n` +
        `An approval authority has been transferred to you by *${currentManager['Employee Name']}*:\n\n` +
        `🎫 *Ticket ID:* *${ticketId}*\n` +
        `🏢 *Client Name:* *${clientName}*\n` +
        `📂 *Category:* *${category}*\n` +
        `👤 *Completed By:* *${completedByName}* (${completedBy})\n` +
        `📝 *Task Details:* ${description}\n\n` +
        `💬 *Transfer Reason/Remarks:* *${remarks || 'No remarks provided.'}*\n\n` +
        `👉 Kindly log in to your Pending Approvals dashboard to review and approve/reject this ticket.\n\n` +
        `~ Work Track System`),
  timerStarted: ({user,ticketId,clientName,category,priority,tat,description}) => (`⏱️ *TASK TIMER STARTED (COUNTDOWN)* ⏱️\n` +
        `---------------------------------\n` +
        `Hello *${user['Employee Name']}*,\n\n` +
        `Your countdown timer is now live for *Ticket ID: ${ticketId}*:\n\n` +
        `🎫 *Ticket ID:* *${ticketId}*\n` +
        `🏢 *Client Name:* *${clientName}*\n` +
        `📂 *Category:* *${category}*\n` +
        `⚡ *Priority:* *${priority}*\n` +
        `🎯 *Allocated TAT:* *${tat} Minutes*\n` +
        `📝 *Task Description:* ${description}\n\n` +
        `📌 Please focus on completing this task safely within your target TAT limits!\n\n` +
        `~ Work Track System`),
  chatMessage: ({recipientObj,senderName,taskId,messageText,clientName}) => (`💬 *NEW CHAT MESSAGE RECEIVED* 💬\n` +
            `---------------------------------\n` +
            `Hello *${recipientObj['Employee Name']}*,\n\n` +
            `You have received a new message regarding your active *Ticket ID: ${taskId}*:\n\n` +
            `🎫 *Ticket ID:* *${taskId}*\n` +
            `🏢 *Client Name:* *${clientName}*\n` +
            `👤 *Sender:* *${senderName}*\n` +
            `💬 *Message:* "${messageText}"\n\n` +
            `👉 Kripya work track panel me jaakar chat box check karein aur response dein.\n\n` +
            `~ Work Track System`),
};
