// Copy message expressions verbatim from the checked-in Apps Script, not its send logic.
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../../appscript/code.gs', import.meta.url), 'utf8').split(/\r?\n/);
export const templateSpecs = [
  ['welcome', 162, 'newUser'],
  ['ticketAssigned', 2610, 'assignedUserNotify,newTicket,tatVal,planDateStr,assignContext'],
  ['ticketReassigned', 1582, 'newUser,ticketId,clientName,priority,tatVal,planDateStr,fullDesc,assignerText,remarks'],
  ['ticketApproval', 2852, 'approverUser,ticketId,ticketRow,category,actionBy,fullDesc,assignedTAT,actualTimeTaken,userRemarks'],
  ['ticketClosed', 961, 'ticketId,clientName,category,adminUser,adminRole,description,remarks'],
  ['ticketRework', 973, 'ticketId,clientName,category,adminUser,adminRole,description,remarks'],
  ['ticketHrApproved', 951, 'ticketId,clientName,category,adminUser,description'],
  ['leaveRequest', 1795, 'rec,leaveData,sDateStr,eDateStr'],
  ['intimationRequest', 1874, 'rec,intimationData,dateStr'],
  ['requestResult', 2121, 'emoji,type,statusLabel,employeeObj,subType,dateStr,reason,remarks'],
  ['expenseRequest', 2425, 'rec,expenseData'],
  ['expenseResult', 5748, 'emoji,status,employee,expenseId,expenseRow,admin,remarks'],
  ['approvalTransfer', 5841, 'targetManager,currentManager,ticketId,clientName,category,completedByName,completedBy,description,remarks'],
  ['timerStarted', 5431, 'user,ticketId,clientName,category,priority,tat,description'],
  ['chatMessage', 1481, 'recipientObj,senderName,taskId,messageText,clientName'],
];
// Locate declarations by their title instead of assuming line numbers stay fixed.
const titles = { ticketClosed: 'TICKET APPROVED & CLOSED', ticketRework: 'REWORK REQUIRED ALERT', ticketHrApproved: 'HR APPROVED & VERIFIED' };
let output = '// Message wording copied from appscript/code.gs. Generated by extractWhatsAppTemplates.js.\nexport const legacyWhatsAppTemplates = {\n';
for (const [name, line, vars] of templateSpecs) {
  const start = titles[name] ? source.findIndex((s) => s.includes(titles[name]) && s.includes('= `')) : line - 1;
  const end = source.findIndex((s, i) => i >= start && s.trimEnd().endsWith('`;'));
  if (start < 0 || end < start || end - start > 45) throw new Error(`Cannot locate ${name}`);
  const expression = source.slice(start, end + 1).join('\n').replace(/^.*?=\s*/, '').replace(/;\s*$/, '');
  output += `  ${name}: ({${vars}}) => (${expression}),\n`;
}
output += '};\n';
fs.writeFileSync(new URL('../services/whatsappLegacyTemplates.js', import.meta.url), output);
console.log('Copied Apps Script WhatsApp template expressions.');
