// Offline tests only: no real clients, database or WhatsApp provider.
import assert from 'node:assert/strict';
import { buildClientTicketAlerts } from '../services/whatsappClientAlerts.js';
import { enqueueAlerts, processNextAlert } from '../services/whatsappAlerts.service.js';
import { WhatsAppAlertJob } from '../models/whatsappAlertJob.model.js';
import { WhatsAppContact } from '../models/whatsappContact.model.js';
import { WhatsAppIntegration } from '../models/whatsappIntegration.model.js';
WhatsAppIntegration.findById = () => ({ lean: async () => null });
process.env.AKNEXUS_ACCESS_TOKEN = 'fixture';
process.env.AKNEXUS_INSTANCE_ID = 'fixture';
const users = ['Admin', 'Super Admin', 'User', 'HR'].map((Role, i) => ({ 'Employee ID': `E${i}`, 'Employee Name': Role, Role, Status: 'Active' }));
const client = { Client_Id: 'C1', 'Client Name': 'Fixture client', 'Mobile Number': '9876543210', Status: 'Active' };
const ticket = { 'Ticket ID': 'T1', Client_Id: 'C1', Origin: 'Client', 'Task Description': 'Test ticket', 'Employee ID': 'E2' };
const created = buildClientTicketAlerts({ model: 'Ticket', before: null, after: ticket }, ticket, users, [client]);
assert.deepEqual(created.map((e) => e.employeeId || e.clientId), ['E0', 'C1']);
const chat = { MessageID: 'M1', TaskID: 'T1', 'Sender Type': 'client', 'Sender ID': 'C1', Sender: 'Fixture client', Message: 'Hello' };
const events = (message, before = null) => buildClientTicketAlerts({ model: 'Message', before, after: message }, ticket, users, [client]);
assert.deepEqual(events(chat).map((e) => e.employeeId || e.clientId), ['E0', 'E2']);
assert.deepEqual(events({ ...chat, 'Sender Type': 'employee', 'Sender ID': 'E0' }).map((e) => e.employeeId || e.clientId), ['E2', 'C1']);
assert.equal(events(chat, chat).length, 0, 'No alerts on message edits/read receipts');
assert.equal(events({ ...chat, 'Sender ID': 'other-client' }).length, 0);
assert.equal(events({ ...chat, 'Sender ID': '' }).length, 0);
assert(events({ ...chat, Message: 'x'.repeat(9000) }).every((e) => e.message.length <= 4000));
const jobs = new Map();
const contacts = users.map((user, i) => ({ _id: `00000000000000000000000${i}`, employeeId: user['Employee ID'], enabled: true, alertTypes: ['ticket'] }));
WhatsAppContact.find = () => ({ lean: async () => contacts });
WhatsAppAlertJob.updateOne = async (filter, update) => { if (update.$setOnInsert && !jobs.has(filter.key)) jobs.set(filter.key, update.$setOnInsert); };
await enqueueAlerts(created, users, 'same');
await enqueueAlerts(created, users, 'same');
assert.equal(jobs.size, 2, 'One persisted event per recipient');
let claim; let state; let sent = [];
WhatsAppAlertJob.findOneAndUpdate = () => ({ lean: async () => { const row = claim; claim = null; return row; } });
WhatsAppAlertJob.updateOne = async (_, update) => { state = update.$set.state; };
let preference = null;
let linkedContact = null;
WhatsAppContact.findOne = (query) => ({ lean: async () => query.clientId ? linkedContact : preference });
const job = [...jobs.values()].find((row) => row.clientId);
const deps = { readRows: async () => [client], findTicket: async () => ticket, send: async (payload) => { sent.push(payload); return { success: true }; } };
claim = job;
await processNextAlert(deps);
assert.equal(state, 'sent');
assert.equal(sent[0].phone, '+919876543210');
client['Mobile Number'] = '9876543211';
claim = job; await processNextAlert(deps);
assert.equal(sent.at(-1).phone, '+919876543211', 'Use latest client number');
preference = { enabled: false, alertTypes: ['ticket'] };
claim = job; await processNextAlert(deps); assert.equal(state, 'skipped');
preference = null;
claim = job; await processNextAlert({ ...deps, findTicket: async () => ({ ...ticket, Client_Id: 'C2' }) }); assert.equal(state, 'skipped');
client['Mobile Number'] = ''; claim = job; await processNextAlert(deps); assert.equal(state, 'skipped');
assert.equal(sent.length, 2, 'No sends for disabled, missing-number or wrong-client jobs');
linkedContact = { _id: '000000000000000000000099', phone: '+919999999999', enabled: true, alertTypes: ['ticket'], clientId: 'C1' };
claim = job; await processNextAlert(deps);
assert.equal(sent.at(-1).contactId, linkedContact._id, 'Linked contact overrides Client Master number');
linkedContact.enabled = false;
claim = job; await processNextAlert(deps); assert.equal(state, 'skipped');
assert.equal(sent.length, 3);
console.log('PASS: creation/chat routing, sender exclusion, deduplication, current client number, opt-out and ownership checks.');
